### ISSUE TITLE
Photo button in publisher does nothing

### ISSUE THREAD

**Issue by ghost** [martinchodev/Diaspora-Native-WebApp#6]
The photo button of the publisher should open a dialog box asking the user to select a photo application (the gallery, or the camera application).

**Comment by mdev88** [comment]
Hi Augier.
This is already added to the feature wish list. I will close this issue when it's implemented.

Thanks!

**Comment by mdev88** [comment]
Fixed

**Comment by ghost** [comment]
Thx.

**Comment by SansPseudoFix** [comment]
Sorry to reopen this issue, but it's not solved for me =/
- Android 4.4.4 
- Diaspora Native WebApp 1.6.1

Another person on diaspora has the same issue with Galaxy Note 3.

(I "reopen" this one, but I can open another one if you prefer)
